### ISSUE TITLE
Update mattermost-plugin-giphy to v2.0.0

### ISSUE THREAD

**Issue by moussetc** [mattermost/mattermost-marketplace#115]
#### Summary

- Feature: use custom message content with `/gif mysearch "Here is a custom message to display"`
- Feature: by default, `/gif` forces preview before posting (#30). **This change will impact existing plugin installs**, but you can revert to the old `/gif`&`/gifs` behaviour via the plugin configuration, as per your users' preferences.
- Feature: add a "collapsable GIF" option that displays the raw URL (workaround for #12)
- Fix: get better results from Gfycat (less 'no more GIF available errors')
- some refactoring

#### Review reference
https://github.com/moussetc/mattermost-plugin-giphy/releases/tag/v1.4.0-rc1

## Checklist

- [x] [All requirements](https://developers.mattermost.com/extend/plugins/community-plugin-marketplace/#requirements-for-adding-community-plugin-to-the-marketplace) are still met.
- [x] The release also has to follow [Semantic Versioning](https://semver.org/). For plugins in particular this means:
  - If the plugin exposes a public API, breaking changes to the API require a major version bump.
  - If an update requires manual migration actions from the System Admin, a major version bump is required.
- [x] A changelog has been published. The link to it is noted via `release_notes_url` in the manifest.

**Comment by hanzei** [comment]
Nice, thanks for updating the plugin and publishing a new release. :tada: 

I'm wondering it it's worth bumping the major version for this release as it will contain a behaviour change. What do you think?

**Comment by hanzei** [comment]
## Process checklist
- [ ] Create PR to merge changes from upstream into `master`.
- [ ] Request reviews.
- [ ] [Cut plugin release](https://developers.mattermost.com/internal/plugin-release-process).
- [ ] Add release to Marketplace.

**Comment by moussetc** [comment]
> I'm wondering it it's worth bumping the major version for this release as it will contain a behaviour change. What do you think?

Is the behavioural change about the /gifs&/gif -> /gif change? Because I've thought more about it and if I could detect the plugin begin upgraded, I could keep the old behaviour for the previous installs (it would reduce change for existing users). Not sure how to do that, though :thinking: 

Nonetheless, even if I were to do that, the default behaviour of /gif would still change so maybe a major version change would still be in order...

**Comment by hanzei** [comment]
Yes, I'm talking about the ` /gifs&/gif -> /gif ` change. I'm not sure if it's worth doing a migration here. You did the change with a reason and that also applies to existing installations.

**Comment by moussetc** [comment]
Here is th new commit with the version change: https://github.com/moussetc/mattermost-plugin-giphy/commit/9c1f892f3bebea1114c8879ed00d9e5a8a5aa6cd

**Comment by hanzei** [comment]
Awesome, updated the PR and title :+1:

**Comment by hanzei** [comment]
Thanks again for updating your plugin @moussetc :tada:
