### ISSUE TITLE
MS Calendar on Cloud Marketplace: remove E20 label

### ISSUE THREAD

**Issue by aaronrothschild** [mattermost/mattermost-marketplace#150]
Heads up that MS Calendar is highlighted as an E20-only plugin in Mattermost Cloud -- we should remove that label from the Cloud offering, and keep it for self-managed versions only. (given all MM Cloud workspaces have E20-equivalent functionality)

_Issue created from a [Mattermost message](https://community.mattermost.com/_redirect/pl/9wpe4ihgu7noper8k4hn3nom4c) *by @jasonblais*._

**Comment by hanzei** [comment]
Moving to JIRA: https://mattermost.atlassian.net/browse/MM-31005
