### ISSUE TITLE
Change "E20 Only" tag on listings to "E20 and Cloud" 

### ISSUE THREAD

**Issue by aaronrothschild** [mattermost/mattermost-marketplace#160]
Currently, a cloud instance should also have access to the E20 Only plugins, but the label doesn't reflect that.

**Comment by hanzei** [comment]
Thanks for the report. Opened a JIRA: https://mattermost.atlassian.net/browse/MM-32278

**Comment by hanzei** [comment]
Fixed with https://github.com/mattermost/mattermost-marketplace/pull/161
