### ISSUE TITLE
Update Matterpoll to 1.5.0

### ISSUE THREAD

**Issue by kaakaa** [mattermost/mattermost-marketplace#298]
#### Summary

- fix: Allow empty string as third option in modal (https://github.com/matterpoll/matterpoll/pull/362)
- feat: Add Russian localization (https://github.com/matterpoll/matterpoll/pull/364)
- feat: Add "reset vote" button for a poll with single vote setting (https://github.com/matterpoll/matterpoll/pull/382)
- feat: Set color to buttons used for poll operations (https://github.com/matterpoll/matterpoll/issues/267)

#### Review reference

Commit https://github.com/matterpoll/matterpoll/commit/b649ff29beca038018de9be3cbb8610a88950ad7

## Checklist

- [x] [All requirements](https://developers.mattermost.com/extend/plugins/community-plugin-marketplace/#requirements-for-adding-community-plugin-to-the-marketplace) are still met.
- [x] The release also has to follow [Semantic Versioning](https://semver.org/). For plugins in particular this means:
  - If the plugin exposes a public API, breaking changes to the API require a major version bump.
  - If an update requires manual migration actions from the System Admin, a major version bump is required.
- [x] A changelog has been published. The link to it is noted via `release_notes_url` in the manifest.

**Comment by nderambure** [comment]
Thx for this, hope it will be validated for marketplace soon !

**Comment by nderambure** [comment]
Hello, any update on this ? thx !

**Comment by Eleferen** [comment]
Hello. When can we expect an update?

**Comment by nderambure** [comment]
It's been 6 months now and no response from Mattermost dev...
Is there any problem with this extension ?

**Comment by hanzei** [comment]
## Process checklist
- [ ] Create PR to merge changes from upstream into `master`.
- [ ] Request reviews.
- [ ] [Cut plugin release](https://developers.mattermost.com/internal/plugin-release-process).
- [ ] Add release to Marketplace.

**Comment by hanzei** [comment]
Hey everyone,

I've just recently returned to my Marketplace work and I'm still catching up on reviews. The reviews process for this plugin update has been kicked off and reviews are scheduled.

**Comment by hanzei** [comment]
The update is now available through the Marketplace

**Comment by nderambure** [comment]
Thx you @hanzei !
