### ISSUE TITLE
Update mattermost-plugin-botkube 

### ISSUE THREAD

**Issue by mashby2022** [mattermost/mattermost-marketplace#345]
=

#### Summary
- Fix: Change Author to Kubeshop 
- Fix: Change icon to 
![botkube-logo-color-black-portrait](https://user-images.githubusercontent.com/100232008/222801373-500580ee-e283-41e4-be39-af6f62130c53.png)
- Fix: Change tagline to "An app that helps you monitor your Kubernetes cluster, debug critical deployments & gives recommendations for standard practices" 

#### Review reference
No reference 

## Checklist

- [x]  [All requirements](https://developers.mattermost.com/extend/plugins/community-plugin-marketplace/#requirements-for-adding-community-plugin-to-the-marketplace) are still met.
- [x]  The release also has to follow [Semantic Versioning](https://semver.org/). For plugins in particular this means:
  - If the plugin exposes a public API, breaking changes to the API require a major version bump.
  - If an update requires manual migration actions from the System Admin, a major version bump is required.
- [x] A changelog has been published. The link to it is noted via `release_notes_url` in the manifest.

**Comment by hanzei** [comment]
@mashby2022 To which plugin does this issue refer?

**Comment by mashby2022** [comment]
@hanzei The botkube plug-in. I would like to update the website: https://mattermost.com/marketplace/botkube/

**Comment by wiersgallak** [comment]
Updated icon on: https://mattermost.com/marketplace/botkube/

**Comment by wiersgallak** [comment]
Completed author change and added additional text. We are limited in the tagline, so retained what was previously there and added another section.
