### ISSUE TITLE
MS Calendar should show in Marketplace regardless of license 

### ISSUE THREAD

**Issue by DHaussermann** [mattermost/mattermost-marketplace#348]
A change is coming to allow MS Calendar plugin to run regardless of any license type applied to the server.
https://github.com/mattermost/mattermost-plugin-mscalendar/pull/242 

The problem is that the plugin is still hidden from the marketplace based on license. 
We should also remove the `PROFESSIONAL/ENTERPRISE` label as this would also no longer be applicable.

**Comment by hanzei** [comment]
This will be fixe with the next release of the MS Calendar plugin. The existing release can stay as it is.
