### ISSUE TITLE
Notify in MM: Send an Announcement when a plugin has been posted to Marketplace

### ISSUE THREAD

**Issue by aaronrothschild** [mattermost/mattermost-marketplace#72]
Send an Announcement when a `Plugin/New` PR is merged and send to:
-  MM staff channel: Announcements
- MM Community channel: Marketplace (?)

This is to notify Mattermost staff of newly available plugins on the marketplace.

**Comment by levb** [comment]
0/5 A more general webhook, perhaps?

**Comment by hanzei** [comment]
@aaronrothschild @levb :point_up:

**Comment by levb** [comment]
1. My list: Integrations Meeting, Community Configuration
2. Done
3-4: Not sure.

**Comment by hanzei** [comment]
@aaronrothschild Do you agree with the list from Lev? what do you think about 3. and 4.?

**Comment by aaronrothschild** [comment]
Agreed. 
For 3 - I think we could do a better job with the description text for the plugins after reading a few of them.  Some basically just have the plugin name, some have a decent description.  

Key Info:
- Icon?
- Name
- Description
- Version Number and Min Server 
- Release Notes text or link to it (This could optionally be included in a "Props:card" to show up in the RHS perhaps? Not sure if possible to mix Attachments with Meta-Card) 

I was going to write out friendly text, but we need to normalize the "names" across the different plugins.  One is "Github" another is "Jenkins Plugin" for example. 

Not sure about #4 though.  What do you mean?

**Comment by hanzei** [comment]
> For 3 - I think we could do a better job with the description text for the plugins after reading a few of them. Some basically just have the plugin name, some have a decent description.

What is the value of posting the description here? Shouldn't the plugin name make clear what the plugin does.

I haven't thought about the icon. Great idea, but unfortunately it's not feasible.

Post cards still don't work on mobile. Let's use something that is supported on both clients. 

> I was going to write out friendly text, but we need to normalize the "names" across the different plugins. One is "Github" another is "Jenkins Plugin" for example.

I did submit PR to change that.
