### ISSUE TITLE
Marketplace: Link to Gitbook documentation links directly via a "docs" link

### ISSUE THREAD

**Issue by aaronrothschild** [mattermost/mattermost-marketplace#75]
Perhaps add a new config value to Plugin Manifest of "Documentation_URL"? If it exists, then show a link on the UI.

**Comment by hanzei** [comment]
Where would this link be shown in the product? Right now, there isn't a way for users to discover a plugin besides via it's direct interactions like slash commands.

**Comment by hanzei** [comment]
Short term: Use docs url as homepage URL
