### ISSUE TITLE
A separate tab for "Updates Available"

### ISSUE THREAD

**Issue by levb** [mattermost/mattermost-marketplace#81]
It would be nice to have here a tab "Update available" or something similar

_Issue created from a [Mattermost message](https://community.mattermost.com/_redirect/pl/9aope4do1igafr4i5oc7b4nwme) *by @JtheBAB*._

**Comment by asaadmahmood** [comment]
@levb This ticket should not be assigned to whoever is handling design in Integrations/Plugins.
