### ISSUE TITLE
Telemetry: Send the Marketplace search terms to telemetry server (non-custom marketplaces)

### ISSUE THREAD

**Issue by aaronrothschild** [mattermost/mattermost-marketplace#91]
We would like to get better insight on which integrations to work on next.  Understanding what users are searching for would help direct us to discover new integrations and apps to work on in the future.

**Comment by hanzei** [comment]
Given this requires changes in the core product, I've filled a JIRA https://mattermost.atlassian.net/browse/MM-27397
